PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX dcterms: <http://purl.org/dc/terms/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX sdo: <https://schema.org/>

INSERT {
  GRAPH ?g {
    ?term skos:prefLabel ?label .
  }
} WHERE {
  {
    SELECT DISTINCT ?g ?term ?label WHERE {
      VALUES ?g {
        <http://www.w3.org/ns/adms>
        <http://www.opengis.net/ont/geosparql>
        <http://anzsoil.org/def/au/asls/substrate>
        <http://linked.data.gov.au/def/asgs>
      }
      VALUES ?type { rdfs:Class rdf:Property owl:ObjectProperty }
      GRAPH ?g {
        ?term a ?type ;
               rdfs:isDefinedBy ?isDefinedBy .
         # filter out terms that were added by the spatial indexer
         FILTER (?isDefinedBy != <http://www.opengis.net/spec/geosparql/1.0>)
         FILTER (?isDefinedBy != <http://www.opengis.net/ont/geosparql>)

         OPTIONAL { ?term rdfs:label ?label . }

         OPTIONAL { ?term skos:prefLabel ?skosLabel . }
         OPTIONAL { ?term sdo:name ?sdoName . }
         FILTER NOT EXISTS { ?term skos:prefLabel ?skosLabel . }
         FILTER NOT EXISTS { ?term sdo:name ?sdoName . }
      }
    }
  }
}
